import type { SpeciesCarePlanTemplate } from './CarePlanTemplate';

const DOG_TEMPLATE: SpeciesCarePlanTemplate = {
  petType: 'dog',
  version: 1,
  coreSeries: [
    {
      key: 'DHPP_1',
      family: 'DHPP',
      label: 'DHPP (1st)',
      category: 'core',
      doseNumber: 1,
      totalDoses: 3,
      ageWeeksMin: 6,
      ageWeeksMax: 8,
    },
    {
      key: 'DHPP_2',
      family: 'DHPP',
      label: 'DHPP (2nd)',
      category: 'core',
      doseNumber: 2,
      totalDoses: 3,
      ageWeeksMin: 9,
      ageWeeksMax: 11,
      intervalWeeksFromPreviousDose: 3,
    },
    {
      key: 'DHPP_3',
      family: 'DHPP',
      label: 'DHPP (3rd)',
      category: 'core',
      doseNumber: 3,
      totalDoses: 3,
      ageWeeksMin: 12,
      ageWeeksMax: 14,
      intervalWeeksFromPreviousDose: 3,
    },
    {
      key: 'DHPP_4_OPTIONAL',
      family: 'DHPP',
      label: 'DHPP (4th/optional puppy dose)',
      category: 'core',
      doseNumber: 4,
      totalDoses: 4,
      ageWeeksMin: 16,
      ageWeeksMax: 18,
      isOptional: true,
      intervalWeeksFromPreviousDose: 3,
    },
  ],
  rabies: {
    key: 'RABIES_1',
    family: 'Rabies',
    label: 'Rabies',
    category: 'core',
    firstDoseAgeWeeksMin: 12,
    firstDoseAgeWeeksMax: 16,
    boosterAfterMonths: 12,
    repeatIntervalMonthsAfterBooster: 36,
    regionOverrides: {
      IN: 12,
      US: 36,
      EU: 36,
      OTHER: 12,
    },
  },
  nonCoreSeries: [
    {
      key: 'LEPTO_1',
      family: 'Leptospirosis',
      label: 'Leptospirosis (1st)',
      category: 'non-core',
      doseNumber: 1,
      totalDoses: 2,
      ageWeeksMin: 12,
      ageWeeksMax: 14,
      intervalWeeksFromPreviousDose: 3,
      boosterIntervalMonths: 12,
      lifestyleTriggers: ['outdoor', 'mixed'],
      riskLevel: 'high',
    },
    {
      key: 'LEPTO_2',
      family: 'Leptospirosis',
      label: 'Leptospirosis (2nd)',
      category: 'non-core',
      doseNumber: 2,
      totalDoses: 2,
      ageWeeksMin: 15,
      ageWeeksMax: 18,
      intervalWeeksFromPreviousDose: 3,
      boosterIntervalMonths: 12,
      lifestyleTriggers: ['outdoor', 'mixed'],
      riskLevel: 'high',
    },
    {
      key: 'BORDETELLA_1',
      family: 'Bordetella',
      label: 'Bordetella (Kennel Cough)',
      category: 'non-core',
      doseNumber: 1,
      totalDoses: 1,
      ageWeeksMin: 8,
      ageWeeksMax: 12,
      boosterIntervalMonths: 12,
      lifestyleTriggers: ['outdoor', 'mixed'],
      riskLevel: 'medium',
    },
    {
      key: 'LYME_1',
      family: 'Lyme',
      label: 'Lyme (1st)',
      category: 'non-core',
      doseNumber: 1,
      totalDoses: 2,
      ageWeeksMin: 12,
      ageWeeksMax: 16,
      intervalWeeksFromPreviousDose: 3,
      boosterIntervalMonths: 12,
      lifestyleTriggers: ['outdoor'],
      riskLevel: 'high',
    },
    {
      key: 'LYME_2',
      family: 'Lyme',
      label: 'Lyme (2nd)',
      category: 'non-core',
      doseNumber: 2,
      totalDoses: 2,
      ageWeeksMin: 15,
      ageWeeksMax: 20,
      intervalWeeksFromPreviousDose: 3,
      boosterIntervalMonths: 12,
      lifestyleTriggers: ['outdoor'],
      riskLevel: 'high',
    },
  ],
  deworming: {
    startWeeks: [2, 4, 6, 8],
    untilMonths: 6,
    indoorIntervalDays: 30,
    mixedIntervalDays: 21,
    outdoorIntervalDays: 15,
    adultIntervalMonths: 3,
  },
};

const CAT_TEMPLATE: SpeciesCarePlanTemplate = {
  petType: 'cat',
  version: 1,
  coreSeries: [
    {
      key: 'FVRCP_1',
      family: 'FVRCP',
      label: 'FVRCP (1st)',
      category: 'core',
      doseNumber: 1,
      totalDoses: 3,
      ageWeeksMin: 6,
      ageWeeksMax: 8,
    },
    {
      key: 'FVRCP_2',
      family: 'FVRCP',
      label: 'FVRCP (2nd)',
      category: 'core',
      doseNumber: 2,
      totalDoses: 3,
      ageWeeksMin: 10,
      ageWeeksMax: 12,
      intervalWeeksFromPreviousDose: 3,
    },
    {
      key: 'FVRCP_3',
      family: 'FVRCP',
      label: 'FVRCP (3rd)',
      category: 'core',
      doseNumber: 3,
      totalDoses: 3,
      ageWeeksMin: 14,
      ageWeeksMax: 16,
      intervalWeeksFromPreviousDose: 3,
    },
    {
      key: 'FVRCP_4_OPTIONAL',
      family: 'FVRCP',
      label: 'FVRCP (4th/optional)',
      category: 'core',
      doseNumber: 4,
      totalDoses: 4,
      ageWeeksMin: 16,
      ageWeeksMax: 18,
      isOptional: true,
      intervalWeeksFromPreviousDose: 3,
    },
  ],
  rabies: {
    key: 'RABIES_1',
    family: 'Rabies',
    label: 'Rabies',
    category: 'core',
    firstDoseAgeWeeksMin: 12,
    firstDoseAgeWeeksMax: 16,
    boosterAfterMonths: 12,
    repeatIntervalMonthsAfterBooster: 36,
    regionOverrides: {
      IN: 12,
      US: 36,
      EU: 36,
      OTHER: 12,
    },
  },
  nonCoreSeries: [
    {
      key: 'FELV_1',
      family: 'FeLV',
      label: 'FeLV (1st)',
      category: 'non-core',
      doseNumber: 1,
      totalDoses: 2,
      ageWeeksMin: 8,
      ageWeeksMax: 10,
      intervalWeeksFromPreviousDose: 3,
      boosterIntervalMonths: 12,
      lifestyleTriggers: ['outdoor', 'mixed'],
      riskLevel: 'high',
    },
    {
      key: 'FELV_2',
      family: 'FeLV',
      label: 'FeLV (2nd)',
      category: 'non-core',
      doseNumber: 2,
      totalDoses: 2,
      ageWeeksMin: 11,
      ageWeeksMax: 14,
      intervalWeeksFromPreviousDose: 3,
      boosterIntervalMonths: 12,
      lifestyleTriggers: ['outdoor', 'mixed'],
      riskLevel: 'high',
    },
    {
      key: 'BORDETELLA_CAT_1',
      family: 'Bordetella',
      label: 'Bordetella (Cat)',
      category: 'non-core',
      doseNumber: 1,
      totalDoses: 1,
      ageWeeksMin: 8,
      ageWeeksMax: 12,
      boosterIntervalMonths: 12,
      lifestyleTriggers: ['outdoor', 'mixed'],
      riskLevel: 'medium',
    },
  ],
  /** Aligned with DewormingEngine: same early milestones as dogs (2–8 weeks). */
  deworming: {
    startWeeks: [2, 4, 6, 8],
    untilMonths: 6,
    indoorIntervalDays: 30,
    mixedIntervalDays: 21,
    outdoorIntervalDays: 15,
    adultIntervalMonths: 3,
  },
};

export const CARE_PLAN_TEMPLATES: Record<'dog' | 'cat', SpeciesCarePlanTemplate> =
  {
    dog: DOG_TEMPLATE,
    cat: CAT_TEMPLATE,
  };
