import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description:
    "Terms of use for the Pawfect pet health scheduling application — subscriptions, disclaimers, and governing law.",
};

export default function TermsPage(): React.ReactElement {
  return (
    <div className="py-24 md:py-32">
      <article className="prose prose-stone mx-auto max-w-3xl px-4 dark:prose-invert sm:px-6 lg:px-8">
        <p className="not-prose text-sm font-medium uppercase tracking-wide text-stone-500">Pawfect</p>
        <h1>Terms &amp; Conditions</h1>
        <p className="text-sm text-stone-500">Last updated: April 1, 2026 &nbsp;|&nbsp; Effective: April 1, 2026</p>

        <aside className="not-prose my-8 rounded-lg border border-amber-200 bg-amber-50 p-4 text-stone-800 dark:border-amber-900/50 dark:bg-amber-950/40 dark:text-stone-200">
          <p className="m-0 text-sm font-semibold">Not a medical device — informational use only</p>
          <p className="mt-2 mb-0 text-sm leading-relaxed">
            Pawfect is not a medical device and does not diagnose, treat, cure, or prevent any veterinary or medical
            condition. Vaccination and deworming schedules are general informational reminders based on published
            veterinary protocols. They are not a substitute for professional veterinary examination and advice. Always
            consult a licensed veterinarian before making any health decisions for your pet.
          </p>
        </aside>

        <h2>1. Acceptance of terms</h2>
        <p>
          By downloading, installing, or using the Pawfect application or website (&quot;Service&quot;), you agree to be
          bound by these Terms &amp; Conditions (&quot;Terms&quot;). If you do not agree, do not use the Service.
        </p>

        <h2>2. The service</h2>
        <h3>2.1 What Pawfect provides</h3>
        <p>
          Pawfect provides scheduling, reminder, and record-keeping tools designed to help pet owners track and manage
          pet health activities — including vaccinations, deworming, and vet visits — for dogs and cats.
        </p>
        <h3>2.2 What Pawfect does not provide</h3>
        <p>The Service is informational software only. Pawfect explicitly does not:</p>
        <ul>
          <li>Provide veterinary advice, diagnosis, or treatment recommendations.</li>
          <li>Constitute a licensed veterinary practice or telemedicine service.</li>
          <li>Function as a regulated medical device.</li>
          <li>Guarantee that any schedule, reminder, or protocol is appropriate for your specific pet&apos;s health condition.</li>
        </ul>
        <p>
          Health timelines generated by Pawfect are based on widely accepted veterinary protocols (e.g., WSAVA
          guidelines) and the pet profile information you input. Individual pets may have different needs. Your
          veterinarian&apos;s guidance supersedes any schedule generated by the app.
        </p>

        <aside className="not-prose my-6 rounded-md border border-stone-200 bg-stone-50 p-4 text-sm text-stone-800 dark:border-stone-700 dark:bg-stone-900/50 dark:text-stone-200">
          <p className="m-0 font-semibold">Play Store app description disclaimer (Google Play health policy)</p>
          <p className="mt-2 mb-0 italic">
            &quot;Pawfect is not a medical device and does not diagnose, treat, cure, or prevent any veterinary or
            medical condition. Always consult a licensed veterinarian for advice, diagnosis, or treatment.&quot;
          </p>
        </aside>

        <h2>3. Eligibility &amp; accounts</h2>
        <p>
          You must be 18 years of age or older to use the Service. By using Pawfect, you represent that you meet this age
          requirement.
        </p>
        <p>You are responsible for:</p>
        <ul>
          <li>Providing accurate pet profile information to generate appropriate schedules.</li>
          <li>Maintaining the confidentiality of your account credentials.</li>
          <li>All activity that occurs under your account.</li>
        </ul>
        <p>
          Notify us immediately at{" "}
          <a href="mailto:legal@pawfect.app" className="text-stone-700 underline dark:text-stone-300">
            legal@pawfect.app
          </a>{" "}
          if you suspect unauthorized access to your account.
        </p>

        <h2>4. Subscriptions &amp; billing</h2>
        <h3>4.1 Free plan</h3>
        <p>
          The Free plan provides access to basic scheduling features for up to 1 pet, with 3 months of history. No
          payment is required.
        </p>
        <h3>4.2 Paid plans</h3>
        <p>
          Care+ (₹149/month, up to 3 pets) and Family (₹299/month, up to 10 pets) plans are available. Paid subscriptions
          are processed exclusively through Google Play Billing (Android) or Apple App Store (iOS), as required by
          applicable platform policies.
        </p>
        <h3>4.3 Auto-renewal &amp; cancellation</h3>
        <p>
          Paid plans renew automatically at the end of each billing cycle unless cancelled before the renewal date. To
          cancel, manage your subscription through your Google Play or Apple App Store account settings. Refunds are
          governed by the applicable platform&apos;s refund policy (Google Play or Apple App Store), unless otherwise
          required by Indian law.
        </p>
        <h3>4.4 Price changes</h3>
        <p>
          We reserve the right to modify subscription pricing with at least 30 days&apos; advance notice via in-app
          notification or email.
        </p>

        <h2>5. Health content disclaimer</h2>
        <p>The vaccination schedules, deworming intervals, and life stage milestones provided in Pawfect are:</p>
        <ul>
          <li>Based on general protocols from recognized veterinary associations (such as WSAVA and Indian veterinary guidelines).</li>
          <li>Customized to your pet&apos;s species, date of birth, and lifestyle inputs as you provide them.</li>
          <li>Informational reminders only — not a clinical recommendation for your specific pet.</li>
        </ul>
        <p>
          Pawfect expressly disclaims any liability arising from reliance on app-generated health schedules without
          veterinary consultation. Late, missed, or incorrect inputs by the user may result in inaccurate schedule
          generation. Pawfect is not responsible for any adverse health outcome.
        </p>

        <h2>6. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Misuse the Service or attempt to access other users&apos; data.</li>
          <li>Enter fraudulent, false, or intentionally misleading pet health records.</li>
          <li>Use the Service for commercial resale or redistribution without our written permission.</li>
          <li>Reverse engineer, decompile, or attempt to extract source code from the app.</li>
          <li>Use the Service in any manner that violates applicable Indian or international law.</li>
        </ul>

        <h2>7. Intellectual property</h2>
        <p>
          All Pawfect branding, software, designs, text, graphics, and content are owned by or licensed to Pawfect and
          protected by applicable intellectual property laws. You are granted a limited, non-exclusive, non-transferable,
          revocable license to use the app for personal, non-commercial pet care management.
        </p>

        <h2>8. Third-party services</h2>
        <p>
          The Service may integrate with third-party services (e.g., cloud storage providers, analytics platforms). Your
          use of those services is subject to their respective terms and privacy policies. Pawfect is not responsible for
          third-party services.
        </p>

        <h2>9. Disclaimers</h2>
        <p>
          THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND,
          EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY, OR
          NON-INFRINGEMENT.
        </p>
        <p>We do not warrant that:</p>
        <ul>
          <li>The Service will be uninterrupted, error-free, or free of viruses.</li>
          <li>Generated pet health schedules will be appropriate for your specific pet.</li>
          <li>Information in the app is complete, accurate, or current.</li>
        </ul>

        <h2>10. Limitation of liability</h2>
        <p>
          To the maximum extent permitted by applicable Indian law, Pawfect and its officers, employees, and affiliates
          shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but
          not limited to:
        </p>
        <ul>
          <li>Loss of data or pet health records.</li>
          <li>Adverse health outcomes arising from reliance on app-generated schedules.</li>
          <li>Business interruption or loss of revenue.</li>
        </ul>
        <p>
          Our total liability for any claim arising from the Service shall not exceed the amount you paid us in the 12
          months preceding the claim.
        </p>

        <h2>11. Indemnification</h2>
        <p>
          You agree to indemnify and hold harmless Pawfect from any claims, losses, damages, or costs (including legal
          fees) arising from your breach of these Terms or your misuse of the Service.
        </p>

        <h2>12. Governing law &amp; jurisdiction</h2>
        <p>
          These Terms are governed by the laws of India. Any dispute arising from these Terms shall be subject to the
          exclusive jurisdiction of the courts at Bengaluru, Karnataka, India.
        </p>

        <h2>13. Changes to these terms</h2>
        <p>
          We may update these Terms from time to time. We will notify you of material changes via in-app notification or
          email at least 14 days before changes take effect. Continued use of the Service after changes constitutes
          acceptance.
        </p>

        <h2>14. Contact</h2>
        <p>For questions about these Terms:</p>
        <ul>
          <li>
            Email:{" "}
            <a href="mailto:legal@pawfect.app" className="text-stone-700 underline dark:text-stone-300">
              legal@pawfect.app
            </a>
          </li>
          <li>
            Privacy questions:{" "}
            <a href="mailto:privacy@pawfect.app" className="text-stone-700 underline dark:text-stone-300">
              privacy@pawfect.app
            </a>
          </li>
        </ul>

        <p className="text-sm text-stone-500">
          © 2026 Pawfect. All rights reserved. Governing law: India | Jurisdiction: Bengaluru, Karnataka
        </p>
      </article>
    </div>
  );
}
